### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#10]
This issue is for [https://github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

After taking a cursory review of the code, there seem to be problems with some of the functions. For example `fit_analytic` does not seem to be a recognized function. The code/documentation needs to be updated before a more in-depth review is possible. 

Also, I would recommend a more description naming convention for the package. Functions like 'fit' and 'estimate' are very vague and can be confusing when working with multiple packages at the same time.

**Comment by donaldRwilliams** [comment]
`fit_analytic` is not a function in the package, so not really sure how to address this. If you are referring to the example in estimate.R, then `fit_analytic` is the name of an object--i.e.,

```#' # analytic approach (sample by setting analytic = FALSE)
#' fit_analytic <- estimate(Y, analytic = TRUE)
```

Note also we do not have a function named `fit`.  The function `estimate` estimates GGMs (and note changing names of functions would be quite the change considering the package is already on CRAN, researchers use it, etc.)

**Comment by paulgovan** [comment]
The examples in the README should be updated so that they are stand alone. For example, the fit_analytic object is not defined in the README, so these examples are not reproducible. I would also recommend checking the other documentation for similar issues.

**Comment by donaldRwilliams** [comment]
I see that now. I will fix it and check all the examples !

**Comment by jayrobwilliams** [comment]
Another option would be to include `fit_analytic` as a data object in the package, as `bfi` is currently. I'll also note that this issue is included in the paper as well as the README.

**Comment by donaldRwilliams** [comment]
Hi, yes, I fixed this.
