### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jayrobwilliams** [donaldRwilliams/BGGM#11]
This issue is for github.com/openjournals/joss-reviews/issues/2111.

While the package is already on CRAN, it is conventional to also include instructions to install the development version from GitHub in the README. This would be done with
```
library(remotes)
install_github("donaldRwilliams/BGGM")
```

**Comment by donaldRwilliams** [comment]
I will add this !

**Comment by donaldRwilliams** [comment]
I just updated the README to add this and to correct the `fit_analytic` issue. If satisfied, I can close this issue ?

**Comment by jayrobwilliams** [comment]
Yep.
