### ISSUE TITLE
Development Version Fails to Install

### ISSUE THREAD

**Issue by mjbsp** [donaldRwilliams/BGGM#13]
I used the following code to install the most up-to-date version and to try out the new features

`remotes::install_github("donaldRwilliams/BGGM")`

I received the following error message

```
Error: Failed to install 'BGGM' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E>                    ^
E> bggm_fast.cpp:1792:20: error: use of undeclared identifier 'trimatu_ind'
E>   arma::uvec ids = trimatu_ind(size(Rinv_1), 1);
E>                    ^
E> 2 errors generated.
E> make: *** [bggm_fast.o] Error 1
E> ERROR: compilation failed for package ‘BGGM’
E> * removing ‘/private/var/folders/lk/ydlhwp9x3pgbmdxwzltknyc80000gn/T/RtmpJYq7FI/Rinst8dab429856f6/BGGM’
E>       -----------------------------------
E> ERROR: package installation failed
```

I tried installing from githup another package (cowplot), and it installed without issue. I asked a colleauge to try and install BGGM and he also receive an error. I suspect there might be an error in the package itself, but I do not know for sure. Thanks!

**Comment by donaldRwilliams** [comment]
Hmm. It was able to be installed on windows, mac, and linux as of a couple days ago. The error seems to be that I did not include `arma::` for `trimatu_ind`, which I am a bit surprised this was not caught when compiling.

I just fixed that and push the changes to git hub, so you can try to install again.

**Comment by mjbsp** [comment]
Fixed! Thanks.

It did throw up another warning that I think is potentially just a typo. Otherwise it installs and loads!

[   Warning: /private/var/folders/lk/ydlhwp9x3pgbmdxwzltknyc80000gn/T/Rtmp7ynezF/Rbuild93f213c8688/BGGM/man/predict.estimate.Rd:5: unknown macro '\coode'
   Warning: /private/var/folders/lk/ydlhwp9x3pgbmdxwzltknyc80000gn/T/Rtmp7ynezF/Rbuild93f213c8688/BGGM/man/predict.estimate.Rd:29: unknown macro '\coode'](url)

**Comment by donaldRwilliams** [comment]
Nice !

And Indeed. The documentation is still a work in progress. Basically everything is done but going over the documentation to catch errors (no automatic spell check to my knowledge), and will get that error then. 

Basically it is when making the text appear in r code, it should be `\code{}` and not `\coode{}` (...lol...)

Thanks for reporting that !
