### ISSUE TITLE
Code Error in roll_your_own

### ISSUE THREAD

**Issue by mjbsp** [donaldRwilliams/BGGM#24]
This is the same basic error as noted in issue #16 .

Some aspects of the function want the object to be called "fit"

<img width="469" alt="Screen Shot 2020-05-19 at 15 24 37" src="https://user-images.githubusercontent.com/25500769/82331843-f3cb4680-99e4-11ea-9d96-02aadfc2b1a6.png">

**Comment by donaldRwilliams** [comment]
Hi
Thanks ! It seems when I made the function I forgot the key step of changing the fit to object. Note, however, that I did do many tests and so long as the function returns one value or one value for each node, then everything is computed nicely. 

Anyhow, I updated this. I will comb over the rest of the code to check for this kind of error in all the examples.

You can reinstall as well.

**Comment by mjbsp** [comment]
I can confirm that this is fixed. Thanks!
