### ISSUE TITLE
Plotting errors in README

### ISSUE THREAD

**Issue by jayrobwilliams** [donaldRwilliams/BGGM#25]
Some of the `plot()` methods rely on external functions that are not currently imported in the code. The README code below generates an error

```r
Y <- ptsd[,1:5] + 1
fit<- explore(Y, type = "ordinal")
E <- select(fit, alternative = "exhaustive")
plot(E)
# Error in ggnet2(net_neg, node.size = 1, edge.alpha = e[e != 0]/max(e),  : 
#                   incorrect edge.color value
```
as does

```r
Y <- depression_anxiety_t1 + 1
hyp <- c("PHQ2--PHQ9 > PHQ1--PHQ9 > 0; 
          PHQ2--PHQ9 = PHQ1--PHQ9 = 0")
fit <- confirm(Y = Y, hypothesis = hyp, 
               type = "ordinal")
plot(fit) + 
  scale_fill_brewer(palette = "Set2", 
                    name = "Posterior Prob") +
  ggtitle("Confirmatory: Comorbidity Network")
# Error in scale_fill_brewer(palette = "Set2", name = "Posterior Prob") : 
#   could not find function "scale_fill_brewer"
```
The latter one is because `scale_fill_brewer()` is not imported by `BGGM`, but I am unsure as to the cause of the former. Since the latter one isn't essential functionality, I'd just add a `library(ggplot2)` call to the README.

**Comment by donaldRwilliams** [comment]
I will look into this

**Comment by donaldRwilliams** [comment]
The error arose because nothing was actually detected. I will catch that in the function to provide an error message. Also updated the README to not have this issue

**Comment by donaldRwilliams** [comment]
I just pushed the updated changes to the README

**Comment by jayrobwilliams** [comment]
Works for me now.
