### ISSUE TITLE
Statement of Need

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#3]
This issue is for [github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

There is not a clear "statement of need" in either the package documentation or the journal paper. Both provide a description of what the package is useful for, but not necessarily why this package is necessary as opposed to other BGGM software.

**Comment by jayrobwilliams** [comment]
It's not immediately clear from the updated README and paper what the main use and targeted audience is for the package. You can figure this out by reading through the examples, but there should be an explicit setence(s) that spell out what types of problems in which fields this package is intended for.

**Comment by donaldRwilliams** [comment]
Ok. I will add this to the paper and Readme 
later today.

**Comment by donaldRwilliams** [comment]
To follow up on this @jayrobwilliams , I am having a difficult time coming up with a target audience that does not also limit the audience. Really any one that would want to estimate a GGM can use the methods, although it was developed by someone in the social behavioral sciences, if this makes sense.

Anyhow, open to suggestions.

**Comment by jayrobwilliams** [comment]
I think a list of disciplines that commonly employ GGMs with a citation or two for canonical examples of articles that use GGMs would be sufficient for me. The state of the field discussion and comparison to existing packages goes a long way here, but I think a clearly stated example of a problem or two that GGMs are used for in the intro of the paper and README would make the need for BGGM crystal clear.

**Comment by donaldRwilliams** [comment]
Ok. I will add this !

**Comment by donaldRwilliams** [comment]
I am having a bit of a hard time with a "statement of need". Will have to come back to it, as I have some other things to work on.

**Comment by donaldRwilliams** [comment]
To address this comment, we added two sections. The first (What is a Gaussian Graphical Model) stated what a GGM is. And then the second ("Applications") listed several applications with references.

**Comment by jayrobwilliams** [comment]
This is great! Clearly and concisely helps the reader understand what you might want to use a GGM for.

**Comment by donaldRwilliams** [comment]
To address this comment, we clearly stated the need for the package in the paper and the README. This included showcasing examples with actual data and comparisons to other packages
