### ISSUE TITLE
Error for Ordinal Data

### ISSUE THREAD

**Issue by donaldRwilliams** [donaldRwilliams/BGGM#30]
The following error was reported for ordinal data `type = "ordinal"` using the function `estimate`

```
BGGM: Posterior Sampling 
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
****
warning: inv_sympd(): given matrix is not symmetric
error: wishrnd(): given matrix is not symmetric positive definite
**********************************************|
Error in estimate(asd1, type = "ordinal") : 
  wishrnd(): given matrix is not symmetric positive definite
```

**Comment by donaldRwilliams** [comment]
In the documentation there are two common errors. This is the second of the 2: a positive definite error.

The ordinal approach requires sampling thresholds which can be quite difficult if the data
is heavily inflated with values.

In this case, the `type = "mixed"` can be used. Note that `mixed` does not actually have to be mixed data (consisting of continuous and discrete variables), as mentioned in the documentation. It can be ordinal data.

**Comment by donaldRwilliams** [comment]
The data had some variables missing categories. It seems this caused the error. In this case, the mixed data should be used. 

Updated documentation to reflect that each variable must includes all categories. In a future release, perhaps this will be changed but have to look into that.

**Comment by martinobelvederi** [comment]
Dear Donald, I have encountered the same problem using the  type="mixed" option.
However, both using spearman and pearson correlation, the matrix seems to be positive definite
is.positive.definite(mat_data, tol=1e-10)

**Comment by donaldRwilliams** [comment]
What function are you using  ? And are use using the CRAN version  ?

**Comment by martinobelvederi** [comment]
Hello, thanks very much for your reply,
version 2.0 yes, from CRAN

Martino Belvederi Murri
*Ricercatore Universitario*
Istituto di Psichiatria, Dipartimento di Scienze Biomediche e
Chirurgico-Specialistiche
Università degli Studi di Ferrara
Via Fossato di Mortara 64a 44121 Ferrara

*Assistant Professor*
Institute of Psychiatry, Department of Biomedical and Specialty Surgical
Sciences
University of Ferrara
Via Fossato di Mortara 64a 44121 Ferrara, Italy

Tel. +39 0532 236409;  Fax +39 0532 212240

Email: martino.belvederi@gmail.com; martino.belvederimurri@unife.it



Il giorno lun 15 giu 2020 alle ore 18:29 Donald R. Williams <
notifications@github.com> ha scritto:

**Comment by donaldRwilliams** [comment]
Install development version 

if (!requireNamespace("remotes")) { 
  install.packages("remotes")   
}   
remotes::install_github("donaldRwilliams/BGGM")

**Comment by martinobelvederi** [comment]
it worked! thanks a lot and congrats on a great package

**Comment by donaldRwilliams** [comment]
Nice ! And thank you
