### ISSUE TITLE
Real world example problems

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#4]
This issue is for [github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

The package docs provide numerous examples, but ideally there would be some "real world" examples or case studies of how this package solved research problems.

**Comment by jayrobwilliams** [comment]
Taking a look at the `bfi` and `rsa` data objects reveals they are real and not simulated data. I would be satisfied on this front if the paper discussed the substantive questions addressed in these examples.

**Comment by donaldRwilliams** [comment]
We will add this. Also, to address Paul's initial comment, we are planning to write an additional vignette to address his comment. This would include, for example, actual substantive applications as opposed to the examples just showing the implementation in the documentation.

**Comment by donaldRwilliams** [comment]
I added these to the readme, as to keep the paper short as you suggested @paulgovan 

see here for real world examples

suicidal thoughts:
https://github.com/donaldRwilliams/BGGM#Confirmatory

comparing agreeableness for males and females
https://github.com/donaldRwilliams/BGGM#confirmatory-groups

**Comment by jayrobwilliams** [comment]
I am satisfied on this dimension.

**Comment by donaldRwilliams** [comment]
To address this comment, we replaced all the examples in the readme and documentation with actual data. In the readme in particular, now the examples show explicitly how to answer research questions with the package.
