### ISSUE TITLE
Error code when running estimate

### ISSUE THREAD

**Issue by matticervin** [donaldRwilliams/BGGM#40]
I am analyzing a dataset with 5 variables and N ~5,000. Each variable has many zeros so I use the "mixed" method with this code:

``` fit_df <- estimate(df, type = "mixed", prior_sd = 0.5, seed = 1)```

I get this error code:
```
> warning: inv_sympd(): given matrix is not symmetric
> 
> error: wishrnd(): given matrix is not symmetric positive definite
> **************************************************|
> Error in estimate(ocrd, type = "mixed", prior_sd = 0.01, seed = 1) : 
>   wishrnd(): given matrix is not symmetric positive definite
```
I have tried lowering prior_sd to 0.01 without any success.

**Comment by donaldRwilliams** [comment]
Hi:
Before I have a further look, can you try the same thing with `explore` ?

**Comment by matticervin** [comment]
Same issue with explore.
