### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#5]
This issue is for [github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

There are no automated tests for this package that I'm aware of (e.g. travis). I would also recommend submitting this package to CRAN. This would provide a wider use-base for the package.

**Comment by donaldRwilliams** [comment]
Hi:
Thank you for all the great suggestions ! One note is that the package is already on CRAN.

https://cran.r-project.org/web/packages/BGGM/index.html

**Comment by paulgovan** [comment]
Ok then my recommendation would be to update the documentation to reflect that.

**Comment by donaldRwilliams** [comment]
We now have travis and the badge is on the readme

**Comment by donaldRwilliams** [comment]
Closed due to adding travis
