### ISSUE TITLE
Error when trying to run hypothesis-testing analysis

### ISSUE THREAD

**Issue by michellehunsche** [donaldRwilliams/BGGM#53]
I was trying to run a line of code to test whether a variable is most strongly related to all other nodes (ie most central) in a network of 7 variables. Here is an example of what the code looks like:

hyp1_SRS <- c("ToM--SRS > CBCL--SRS; ToM--SRS < CBCL--SRS; ToM--SRS = CBCL--SRS")
 
confirm_hyp1_SRS <- bggm_missing(imp_socanxnet,hyp1_SRS,iter = 50000,type="mixed", mixed_type=c(0,0,0,0,0,0)) 

And I'm getting this error:
 
Error in bggm_missing(imp_socanxnet, hyp1_SRS, iter = 50000, type = "mixed",  : 
  object 'fits' not found

I'm relatively new to R and network analysis and not sure what could be the cause of this error. Any advice is much appreciated!

**Comment by donaldRwilliams** [comment]
Hi:

`bggm_missing` does not currently work for testing hypotheses like that. However, you can use the function `confirm`. The downside is that the missing data will be removed for now.

**Comment by michellehunsche** [comment]
That's helpful, thank you!
