### ISSUE TITLE
Feature Request: Strength Centrality Comparison between networks

### ISSUE THREAD

**Issue by mikaelr88** [donaldRwilliams/BGGM#57]
It would be great if there was a straightforward way to compare node strength centrality between two networks (e.g. T1 & T2).

**Comment by donaldRwilliams** [comment]
Thank you for the suggestion. What is implemented in BGGM are things that we have published papers on or that we are confident make sense. For centrality, this is intentionally not included in BGGM for those reasons

**Comment by donaldRwilliams** [comment]
@mikaelr88 note also I can provide an example in the documentation if that will help :-)

**Comment by mikaelr88** [comment]
That would be great, thank you!

**Comment by donaldRwilliams** [comment]
@mikaelr88 

See here

```
library(BGGM)
library(ggplot2)
library(NetworkToolbox)

Y1 <- subset(bfi, gender == 1)[,1:5]
Y2 <- subset(bfi, gender == 2)[,1:5]

fit1 <- estimate(Y1)
fit2 <- estimate(Y2)

# define custom function
func <- function(x, ...){
  NetworkToolbox::strength(x, ...)
} 

strength1 <- roll_your_own(fit1, FUN = func, select = TRUE)
strength1

strength2 <- roll_your_own(fit2, FUN = func, select = TRUE)
strength2


plot(strength2) +
  ggplot2::ggtitle("Strength")

# compute difference
strength_diff <- t(strength1$results) - t(strength2$results)

# compute credible interval node 1 difference 
quantile( strength_diff[,1], probs = c(0.05, 0.95)) 

# plot difference
hist(strength_diff[,1])
```


Note where `func` is. You can compute anything you want there. In this case, strength is being computed. Then I got the results and subtracted them for each node which provides the difference in strength.

Hope that helps !

**Comment by mikaelr88** [comment]
Thank you very much, that is extremely helpful!
