### ISSUE TITLE
State of the field

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#7]
This issue is for [github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

"Do the authors describe how this software compares to other commonly-used packages?"

It's pretty clear that the software is useful, but it's not really clear how this software compares to and is better in some way than other software that's currently available. In addition, the background on existing software seems incomplete, as there are numerous packages for building Bayesian graphical models.

**Comment by donaldRwilliams** [comment]
We are happy to include this. To our knowledge, for GGMs in particular (and not Bayesian networks), there are only two R packages (BDgraph and beam). We are not aware of others, but can take another look.

**Comment by donaldRwilliams** [comment]
We added a note to the README. To our knowledge, there is no R package that includes all the algorithms and methods.

**Comment by jayrobwilliams** [comment]
The updated README and paper note that there is no R package that implements all of these methods. Are there other R packages that implement different subsets of these methods? If so, they would be important to mention here. Is the new c++ implementation faster than these packages? This would also be good to mention.

**Comment by donaldRwilliams** [comment]
OK. I will add this

**Comment by jayrobwilliams** [comment]
I am satisfied with the way these issues have been addressed.

**Comment by donaldRwilliams** [comment]
To address these comments, we followed the suggestions of the reviewers to include a section comparing to other software.
