### ISSUE TITLE
Changing credibility level in estimate function

### ISSUE THREAD

**Issue by tsbaguley** [donaldRwilliams/BGGM#72]
For some reason I can't change the credibility level from 0.95. (Working from the CRAN version 2.03).

e.g., 

fit <- estimate(Y, type = "continuous", cred=0.99)

... or at least the lower and upper bounds from summary(fit) don't change. I have probably made a stupid error, but I've run out of brain cells to resolve this today.

**Comment by donaldRwilliams** [comment]
Hi.
That would all be done after fitting. The reason is that then you do not have to re fit model in the event you wanted different `cred`.

see here

```
library(BGGM)

Y <- ptsd

fit <- estimate(Y)

summary(fit, cred = 0.90)

select(fit, cred = 0.90)


summary(fit, cred = 0.99)

select(fit, cred = 0.99)

# need to customize with ggplot to look nice
plot(summary(fit, cred = 0.99))

```

**Comment by tsbaguley** [comment]
Thank you so much - I knew it would be something basic. I'm doing some exploratory work and the 90% credibility plot makes more sense in this context. I love the package.

**Comment by donaldRwilliams** [comment]
No problem. 
And thanks  !
