### ISSUE TITLE
Network comparison for dependent cases

### ISSUE THREAD

**Issue by xinkaidupsy** [donaldRwilliams/BGGM#77]
Hi Donald,

I'm having six conditions and wish to compare network properties under these conditions. To save participants, I'm thinking about using within-subject design instead of recruiting different groups of people for different conditions. However, this means that cases in different conditions would be dependent. I was wondering if BGGM network comparison can allow for this.

I was also wondering if I can estimate an overall BGGM with all the variables plus a condition variable when cases are dependent. 

Thanks in advance for the answer.
Best,
Xinkai

**Comment by donaldRwilliams** [comment]
"Not really because the goal is to see whether pairwise interactions between variables would differ across conditions, and also whether network structures change in response to conditions."

I guess I am still a bit confused. How would simply comparing the edges not answer that question ?

**Comment by xinkaidupsy** [comment]
> "Not really because the goal is to see whether pairwise interactions between variables would differ across conditions, and also whether network structures change in response to conditions."
> 
> I guess I am still a bit confused. How would simply comparing the edges not answer that question ?

Ah the goal is to compare edges, e.g, the edge between variable A & B, in different experimental conditions, rather than comparing the strength of edgeAB with edgeBC within the same network. I'm also interested in comparing the sum of edges across different conditions. Also, I also wish to know difference in network connectivity caused by condition differences, this can't be done with edge comparisons in the same condition.

**Comment by donaldRwilliams** [comment]
you can do something like that in BGGM. you can legit compare whatever you want by defining your own function..

**Comment by xinkaidupsy** [comment]
Ok awesome. Thanks for the answer!
