### ISSUE TITLE
Paper length

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#8]
This issue is for [github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

The paper is well over the max length of 1000 words. It looks like the paper is basically the same as the README. I think the paper is meant to be more high-level. Examples and detailed descriptions of the package are not really necessary and can be reserved for the README, wiki, etc.

**Comment by donaldRwilliams** [comment]
what is your suggestion here ?

We wrote the paper specifically for JOSS and then figured it would also make a nice README. As opposed to just submitting to JOSS our previously written README, etc.

**Comment by paulgovan** [comment]
Take a look at the journal's instructions for authors.

**Comment by donaldRwilliams** [comment]
in our experience there is typically flexibility surrounding the instructions for author. In this case, the packing includes the software implementation of novel methods that were introduced in 3 peer-reviewed papers. Hence why it is on the longer side. But happy to shorten if the editor also thinks it should be shorter.

**Comment by donaldRwilliams** [comment]
We took your advice and now provide an overview of the package..

**Comment by donaldRwilliams** [comment]
We address this by making the paper much more a "high level" overview which followed the suggestion of the reviewer.
