### ISSUE TITLE
select function is not working

### ISSUE THREAD

**Issue by andrewpython** [donaldRwilliams/BGGM#83]
Hi, 

I used select function in BGGM to estimate network, but the function is not working. I use the bfi data  from psych package and please see the code below. Thanks so much for your help in advance!

library(psych)
library(BGGM)

bfidata <- bfi[, 1:25]

fit <- estimate(bfidata)
select(fit)
select(fit, cred = 0.95, alternative = "two.sided")
#these codes are not working. The error message is shown below:

_Error in UseMethod("select") : 
  no applicable method for 'select' applied to an object of class "c('BGGM', 'estimate', 'default')"**__

**Comment by donaldRwilliams** [comment]
Thank you for this issue !

I would try restarting R. Several other packages have a select function, and that might be causing the issue.

So when I restart R, and run **only** the following it works

```
library(psych)
library(BGGM)

bfidata <- bfi[, 1:25]

fit <- estimate(bfidata)
select(fit)
```

![image](https://user-images.githubusercontent.com/19657194/144532531-eed4e9fb-97ef-428a-a901-fc462e29aa02.png)

**Comment by andrewpython** [comment]
Thank you so much for your quick response! I have just run the code and it's working this time. Much appreciated!

**Comment by donaldRwilliams** [comment]
Nice !
