### ISSUE TITLE
Paper references

### ISSUE THREAD

**Issue by paulgovan** [donaldRwilliams/BGGM#9]
This issue is for [github.com/openjournals/joss-reviews/issues/2111](https://github.com/openjournals/joss-reviews/issues/2111).

The references are not rendered in the paper. I see that they appear in the package docs, so I'm thinking that there is something wrong with the way the paper is being built.

**Comment by donaldRwilliams** [comment]
Hmm.
Not sure. Here is a link to the paper. There may be an issue now that the paper had to be moved to the root. will have to take a look later today

https://psyarxiv.com/t2cn7/

**Comment by donaldRwilliams** [comment]
We have updated the references.

**Comment by donaldRwilliams** [comment]
Pretty sure this can be closed.
