### ISSUE TITLE
Library not running on Arm based Mac

### ISSUE THREAD

**Issue by aliyanishfaq** [donaldRwilliams/BGGM#92]
Hi, I have been trying to install this library to compare GGMs, and it is not being installed on my M1 Mac. After debugging, I think it might be a compatibility issue because the library runs when I try it on Google Colab. It would be helpful to know if there is a compatibility issue, or something completely different. Can this be kindly looked into?

I am attaching a screenshot of the error I am getting while trying to install it, if it helps.
![Screenshot 2023-11-27 at 4 55 01 PM](https://github.com/donaldRwilliams/BGGM/assets/63409543/3910c537-08f3-42df-8dda-f456fc197585)

**Comment by ph-rast** [comment]
BGGM 2.1.1 upgraded the C++ libraries. The package builds (https://github.com/donaldRwilliams/BGGM/actions/runs/8389669043) on the latest MacOS (Monterey 12.7.3) and I assume it resolves this issue. I'll close this issue - feel free to open it again if you still run into a problem
