### ISSUE TITLE
Using BGGM::select in combination with BGGM::explore gives par cors above 1

### ISSUE THREAD

**Issue by KarolineHuth** [donaldRwilliams/BGGM#93]
The following code will give partial correlations above one. I cannot share the code publicly but will share it via email with Phillipe. 

The issue lies in the select function. the explore function will give partial correlations between -1 and 1 as expected.

```
data <- readRDS("N0648_1_cleaned.rds")

fit <- BGGM::explore(data, type = "continuous", prior_sd = .5, seed = NULL)
out <- summary(fit)
max(out$dat_results$Post.mean)
# not above one

out_select <- BGGM::select(fit)
max(out_select$pcor_mat)
# Above 1
```

**Comment by ph-rast** [comment]
Looks like this [commit](https://github.com/donaldRwilliams/BGGM/commit/a264c440006069e5f171494d9618bae57f4d6566) did the trick - I'm closing this issue
